### DISCUSSION TITLE
A Humble Proposal for Extracting Content Source Entities

### DISCUSSION THREAD

**Discussion by tomerlichtash** [tomerlichtash/mels-loop#235] [Ideas]
Currently each source has a reference attached to an actual markdown file.

The problem as we currently see it is that we want to reference multiple items to a single entity, and that entity should also present metadata. e.g. Two references to Librazette, while the Librazette entity reveals its own cover image, but also allowing both references to present their own cover photo, without overriding a single cover photo opportunity.

In order to accomplish that, I propose the following structure:
```
/public/sources
└── parent1
    ├── index.en.md
    ├── index.he.md
    ├── ref1
    │   ├── assets.md
    │   ├── index.en.md
    │   ├── index.he.md
    │   └── meta.md
    └── ref2
        ├── assets.md
        ├── index.en.md
        ├── index.he.md
        └── meta.md
```

- Each `Parent` refers to a bibliographic source (which might have multiple references to it), e.g.: `Librazette`.
- Each `ref` represents a singular reference to the parent source (e.g. An article, an ad, a piece of some sort).
- Each parent or ref `id` is similar to the folder they reside in.

The parent and ref `metadata` is described via `index.[locale].md`, like so:

Parent:
```
---
title: Parent 1 Title
---
```

or, for Ref:
```
---
meta:
  - title: Source 1 Title
bibliography:
  - url: http://example.com
  - page?: 4 <optional>
  - author?: <optional>
assets:
  - asset1id
  - asset2id
assets_labels:
  - asset1id: some label in english
  - asset2id: another label in english
---
```

A `ref` entity can have common props for multilingual entries, so `ref` can also have data described in `meta.md`, like so:

```
---
date: 12.12.1992
---
```

Another special feature for `ref` is describing assets via `assets.md`, which contains a URL to a media assets. This can be optimized so `assets.md` would reference to assets IDs, once we get those in place, somehow, but currently the description is via a direct URL, like so:

```
---
asset1id: "http://asset1url"
asset2id: "http://asset2url"
asset3id: "http://asset3url"
---
```

The idea here is that different languages might want to refer to different assets, and probably will have to use different label captions.

These are my initial thoughts on the matter. A draft for this structure can be found in this branch: [export-source-entity](https://github.com/tomerlichtash/mels-loop/tree/export-source-entity).
